version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker image
          command: docker build .
workflows:
  version: 2
  all-tests:
    jobs:
      - build
